

//------------------------------------------------------------------------------
// <auto-generated>
//  * 文件名称：T4模板客户端生成器
//  * 文件作者：新生帝
//  * 编写日期：2016-02-11 22:28:45
//  * 版权所有：中山赢友网络科技有限公司
//  * 企业官网：http://www.winu.net
//  * 开源协议：GPL v2 License
//  * 文件描述：一切从简，只为了更懒！
//  * 使用步骤：1、修改下面 solutionDir 目录路径，必须是电脑对应的绝对路径并带 \ 结尾。
//  *                 2、设置数据库连接字符串
//  *                 3、使用快捷键：Ctrl+S 或者点击工具栏 保存 按钮即可生成所有文件。
//  *                 4、生成成功之后会弹出提示框，提示是否加载，选择全部加载！
//  * 特别注意：重新保存文件会导致代码重新生成，请慎重使用！
// </auto-generated>
//------------------------------------------------------------------------------

// 设置解决方案目录：string solutionDir=@"F:\Github\AppSoft2.0.IO\";


// 设置数据库连接字符串：MssqlHelper.connStr="Server=DESKTOP-ADRG1K6;Database=DotDot;Uid=sa;Password=000000;";


// 获取数据库所有的表和视图：List<string> tableNames=MssqlHelper.GetTables();



	// 生成所有实体层实体类文件：MssqlHelper.CreateEntityFile(tableName,solutionDir);

	
	// 生成所有仓储接口层仓储接口类文件：MssqlHelper.CreateIRepositoryFile(tableName,solutionDir);

	
	// 生成所有仓储层仓储类文件：MssqlHelper.CreateRepositoryFile(tableName,solutionDir);

	
	// 生成所有服务接口层服务接口类文件：MssqlHelper.CreateIServicesFile(tableName,solutionDir);

		
	// 生成所有服务层服务类文件：MssqlHelper.CreateServicesFile(tableName,solutionDir);

	

// 生成App.Site项目文件夹App_Code的父控制器类：MssqlHelper.CreateBaseController(tableNames,solutionDir);


// 生成App.RESTful API项目文件夹App_Code的父Api控制器类：MssqlHelper.CreateBaseApiController(tableNames,solutionDir);

